name: Smart Digital India Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install Dependencies
        run: cd Smart-Digital-India && flutter pub get

      - name: Verify Code and Build
        run: cd Smart-Digital-India && flutter analyze
        
